### PR TITLE
Custom view file location

### PR DESCRIPTION
**Pull request by aseroff**
I was able to solve the prepend_view_path approach. Definitely seems like the most elegant approach to solving the issue. I tested it minimally to make sure it progressed through the paths properly, and it seemed to to me.

### CODE REVIEW

**Comment by simmerz** [comment]
@wakproductions does this branch work for you?

**Comment by aseroff** [comment]
Oh shoot I see something I need to fix. One second.

**Comment by aseroff** [comment]
Okay, now try the branch :)

**Comment by wakproductions** [comment]
@aseroff you should probably do a backmerge of master on your branch
image

**Comment by aseroff** [comment]
@wakproductions thanks, how bout now

**Comment by wakproductions** [comment]
> It's working 👍 That deprecation warning is like a game of Where's Waldo though. It's gonna blindside some folks whenever the change becomes official.

I just want to clarify that I approve of this PR. I think merging would be a good idea. The upcoming deprecation should be documented somewhere though so that existing users can easily find out why their program breaks once it goes from deprecation warning to requirement.

**Comment by aseroff** [comment]
> > It's working 👍 That deprecation warning is like a game of Where's Waldo though. It's gonna blindside some folks whenever the change becomes official.
> 
> I just want to clarify that I approve of this PR. I think merging would be a good idea. The upcoming deprecation should be documented somewhere though so that existing users can easily find out why their program breaks once it goes from deprecation warning to requirement.
> 
> 

This whole plugin could use some documentation love. Maybe instead of introducing breaking changes I should work on that instead 😬

**Comment by wakproductions** [comment]
> > > It's working 👍 That deprecation warning is like a game of Where's Waldo though. It's gonna blindside some folks whenever the change becomes official.
> > 
> > 
> > I just want to clarify that I approve of this PR. I think merging would be a good idea. The upcoming deprecation should be documented somewhere though so that existing users can easily find out why their program breaks once it goes from deprecation warning to requirement.
> 
> This whole plugin could use some documentation love. Maybe instead of introducing breaking changes I should work on that instead 😬

Yes. Spina/spina-blog are both terrific Ruby tools. I like that these gems allow me to have a nice publishing platform that I can customize without having to deal with PHP problems. It's the CMS that Ruby needs!

**Pull request merged**
